version: '3.8'
services:
  api:
    container_name: api
    build: .
    ports:
      - "81:81"

    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:81
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - OTEL_SERVICE_NAME=Api
  postgres:
    container_name: postgres
    image: postgres:16.1
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=]431*8Z.gC
    volumes:
      - postgres_datadir:/var/lib/postgresql/data

  bitcoind:
    restart: unless-stopped

    container_name: bitcoind
    image: btcpayserver/bitcoin:26.0
    ports:
      - "43782:43782"
      - "39388:39388"
    environment:
      BITCOIN_NETWORK: testnet
      # rpcport and rpcbind seems duplicates, but they are not
      # rpcport is using by some tooling to automatically get
      # the rpcport from the configuration file. Do not remove!
      BITCOIN_EXTRA_ARGS: |
        rpcport=43782
        rpcbind=0.0.0.0:43782
        rpcallowip=0.0.0.0/0
        port=39388
        whitelist=0.0.0.0/0
        maxmempool=500
    expose:
      - "43782"
      - "39388"
    volumes:
      - bitcoin_datadir:/data


  nbxplorer-postgres:
    container_name: nbxplorer-postgres
    image: postgres:16.1
    restart: always
    ports:
      - "4040:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=S{@08[i8i3tX
    volumes:
      - nbxplorer_postgres_datadir:/var/lib/postgresql/data


  nbxplorer:
    image: nicolasdorier/nbxplorer:2.5.0
    container_name: nbxplorer

    restart: always
    ports:
      - "32838:32838"
    environment:
      NBXPLORER_NETWORK: testnet
      NBXPLORER_BTCRESCAN: "true"
      NBXPLORER_BTCSTARTHEIGHT: 5000
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_TRIMEVENTS: 10000
      NBXPLORER_SIGNALFILESDIR: /datadir
      NBXPLORER_POSTGRES: User ID=postgres;Password=S{@08[i8i3tX;Host=nbxplorer-postgres;Port=5432;Database=nbxplorer;
      NBXPLORER_AUTOMIGRATE: 1
      NBXPLORER_NOMIGRATEEVTS: 1
      NBXPLORER_CHAINS: "btc"
      NBXPLORER_NOAUTH: 1
      NBXPLORER_BTCRPCURL: http://bitcoind:43782/
      NBXPLORER_BTCNODEENDPOINT: bitcoind:39388
    volumes:
      - "nbxplorer_datadir:/datadir"
      - "bitcoin_datadir:/root/.bitcoin"
    links:
      - bitcoind
      - nbxplorer-postgres

  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 92;,7&UyU9%s
    command: server --console-address ":9001" /data

#  zipkin:
#    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
#    container_name: zipkin
#    environment:
#      - STORAGE_TYPE=mem
#    ports:
#      - 9411:9411

volumes:
  nbxplorer_datadir:
    driver: local

  bitcoin_datadir:
    driver: local

  postgres_datadir:
    driver: local

  nbxplorer_postgres_datadir:
    driver: local

  minio_storage:
    driver: local

