using System.Reflection;
using System.Text.Json.Serialization;
using Asp.Versioning;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Internal;
using Microsoft.OpenApi.Models;
using Npgsql;
using OpenTelemetry.Resources;
using OpenTelemetry.Trace;
using Prometheus;
using RamzPardakht.ApplicationCore;
using RamzPardakht.ApplicationCore.Entities;
using RamzPardakht.ApplicationCore.Resources;
using RamzPardakht.Infrastructure;
using RamzPardakht.Infrastructure.DbContexts;
using RamzPardakht.WebApi.Common;
using Serilog;

namespace RamzPardakht.WebApi;

public class Startup
{
    public Startup(IConfiguration configuration)
    {
        _configuration = configuration;
    }

    private readonly IConfiguration _configuration;

    public void ConfigureServices(IServiceCollection services)
    {
        services.AddIdentityCore<User>(options =>
            {
                options.User.RequireUniqueEmail = true;
                options.SignIn.RequireConfirmedEmail = true;
                options.Password.RequireDigit = false;
                options.Password.RequireLowercase = false;
                options.Password.RequireUppercase = false;
                options.Password.RequireNonAlphanumeric = false;
            })
            .AddRoles<Role>()
            .AddDefaultTokenProviders()
            .AddErrorDescriber<CustomIdentityErrorDescriber>()
            .AddEntityFrameworkStores<ProjectDbContext>()
            .AddApiEndpoints();

        services.AddLocalization();

        services.AddControllers()
            .AddDataAnnotationsLocalization(options =>
            {
                options.DataAnnotationLocalizerProvider = (_, factory) =>
                    factory.Create(typeof(SharedResource));
            })
            .AddJsonOptions(options =>
                options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter()));

        services.AddCors(corsOption =>
        {
            corsOption.AddDefaultPolicy(
                builder => builder.AllowAnyOrigin()
                    .AllowAnyMethod()
                    .AllowAnyHeader()
                    .SetPreflightMaxAge(TimeSpan.FromMinutes(10)));
        });

        services.AddApiVersioning(o =>
            {
                o.AssumeDefaultVersionWhenUnspecified = false;
                o.DefaultApiVersion = new ApiVersion(1, 0);
                o.ReportApiVersions = true;
                o.ApiVersionReader = new UrlSegmentApiVersionReader();
            })
            .AddMvc()
            .AddApiExplorer(
                options =>
                {
                    options.GroupNameFormat = "'v'VVV";
                    options.SubstituteApiVersionInUrl = true;
                });


        services.AddAuthentication()
            .AddBearerToken(IdentityConstants.BearerScheme);


        services.AddAuthorization(options =>
        {
            options.AddPolicy("admin",
                policy => policy.RequireRole("RamzPardakht:admin"));
            options.AddPolicy("read",
                policy => policy.RequireRole("RamzPardakht:read"));
            options.AddPolicy("write",
                policy => policy.RequireRole("RamzPardakht:write"));
        });

        services.AddHttpContextAccessor();
        services.AddSingleton<ISystemClock, SystemClock>();

        // added handlers to this client will apply to all clients
        services.UseHttpClientMetrics();
        services.UseHttpClientLogRequestResponse(options => _configuration.Bind("LogRequestResponse", options));

        services.AddInfrastructure(_configuration);
        services.AddApplication();

        services.AddEndpointsApiExplorer();
        services.AddSwaggerGen(options =>
        {
            options.SwaggerDoc("v1", new()
            {
                Title = "v1",
                Version = "v1"
            });

            //Locate the XML file being generated by ASP.NET...
            string xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
            string xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
            //... and tell Swagger to use those XML comments.
            options.IncludeXmlComments(xmlPath);

            options.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
            {
                Description = "JWT Authorization header using the Bearer scheme. Example: 'Bearer 12345abcdef'",
                Name = "Authorization",
                In = ParameterLocation.Header,
                Type = SecuritySchemeType.ApiKey,
                Scheme = "Bearer"
            });

            options.AddSecurityRequirement(new OpenApiSecurityRequirement()
            {
                {
                    new OpenApiSecurityScheme
                    {
                        Reference = new OpenApiReference
                        {
                            Type = ReferenceType.SecurityScheme,
                            Id = "Bearer"
                        },
                        Scheme = "Bearer",
                        Name = "Bearer",
                        In = ParameterLocation.Header,

                    },
                    new List<string>()
                }
            });
        });

        //for more information read
        //https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-logging/?view=aspnetcore-6.0
        //dont log Response if grpc is added it will break; track bug in below issue
        //https://github.com/dotnet/aspnetcore/issues/39317
        services.AddHttpLogging(options => _configuration.Bind("HttpLogging", options));

        services.AddOpenTelemetry().WithTracing(builder =>
        {
            builder.AddSource(typeof(Startup).Assembly.FullName);
            builder.AddSource(typeof(ApplicationCoreSetup).Assembly.FullName);
            builder.AddSource(typeof(InfrastructureSetup).Assembly.FullName);
            //environment set docs
            //https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/trace/extending-the-sdk/README.md#resource-detector
            builder.SetResourceBuilder(ResourceBuilder.CreateDefault().AddEnvironmentVariableDetector());
            //environment set docs
            //https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Exporter.Jaeger/README.md#environment-variables
            builder.AddJaegerExporter();
            builder.AddAspNetCoreInstrumentation();
            builder.AddElasticsearchClientInstrumentation();
            builder.AddHttpClientInstrumentation();
            builder.AddEntityFrameworkCoreInstrumentation(options => options.SetDbStatementForText = true);
            builder.AddNpgsql();
        });

        //https://github.com/prometheus-net/prometheus-net#eventcounter-integration
        // Collect below metrics and more
        //https://www.npgsql.org/doc/diagnostics/metrics.html
        //https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/event-counters?tabs=windows
        //https://docs.microsoft.com/en-us/dotnet/core/diagnostics/available-counters
        var eventCounter = EventCounterAdapter.StartListening();

        //https://github.com/prometheus-net/prometheus-net#net-6-meters-integration
        var meter = MeterAdapter.StartListening();

        services.AddHealthChecks()
            .AddDbContextCheck<ProjectDbContext>();
    }

    public void Configure(WebApplication app)
    {
        app.UseRequestLocalization(options =>
            options.AddSupportedUICultures("en-US", "fa-IR").SetDefaultCulture("en-US"));

        app.UseSwagger(options => options.RouteTemplate = "api-docs/{documentName}/swagger.json");
        app.UseSwaggerUI(options =>
        {
            options.SwaggerEndpoint("/api-docs/v1/swagger.json", "v1");
        });

        app.UseCors();

        app.UseRouting();

        app.UseSerilogRequestLogging();

        //HTTP request metrics
        //https://github.com/prometheus-net/prometheus-net#aspnet-core-http-request-metrics
        app.UseHttpMetrics();

        //gRPC request metrics
        //https://github.com/prometheus-net/prometheus-net#aspnet-core-grpc-request-metrics
        app.UseGrpcMetrics();

        //https://josef.codes/asp-net-core-6-http-logging-log-requests-responses/
        app.UseHttpLogging();

        app.UseAuthentication();
        app.UseAuthorization();

        app.MapMetrics("/metrics");

        app.MapHealthChecks("/v1/health-check");

        app.MapGroup("/v1/account").MapIdentityApi<User>();

        app.MapControllers();
    }
}
